# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-17 17:01
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import rendering.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(blank=True, max_length=254)),
                ('comments', models.TextField(blank=True)),
                ('subject', models.TextField(blank=True)),
                ('html', models.TextField(blank=True)),
                ('text', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='JSONSchema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(blank=True, max_length=254)),
                ('comments', models.TextField(blank=True)),
                ('schema', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'JSON schema',
            },
            bases=(rendering.models.AutoCleanMixin, models.Model),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='context_schema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rendering.JSONSchema'),
        ),
    ]
